//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ridder.UnitsOfMeasurement.Resources.UnitSymbols {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitSymbols {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitSymbols() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ridder.UnitsOfMeasurement.Resources.UnitSymbols.UnitSymbols", typeof(UnitSymbols).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ac.
        /// </summary>
        internal static string Acre {
            get {
                return ResourceManager.GetString("Acre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atm.
        /// </summary>
        internal static string Atmosphere {
            get {
                return ResourceManager.GetString("Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cal.
        /// </summary>
        internal static string Calorie {
            get {
                return ResourceManager.GetString("Calorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string CanadianDollar {
            get {
                return ResourceManager.GetString("CanadianDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbar.
        /// </summary>
        internal static string Centibar {
            get {
                return ResourceManager.GetString("Centibar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cl.
        /// </summary>
        internal static string Centiliter {
            get {
                return ResourceManager.GetString("Centiliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Century {
            get {
                return ResourceManager.GetString("Century", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm³.
        /// </summary>
        internal static string CubicCentimeter {
            get {
                return ResourceManager.GetString("CubicCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dm³.
        /// </summary>
        internal static string CubicDecimeter {
            get {
                return ResourceManager.GetString("CubicDecimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft³.
        /// </summary>
        internal static string CubicFoot {
            get {
                return ResourceManager.GetString("CubicFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hm³.
        /// </summary>
        internal static string CubicHectometer {
            get {
                return ResourceManager.GetString("CubicHectometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in³.
        /// </summary>
        internal static string CubicInch {
            get {
                return ResourceManager.GetString("CubicInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km³.
        /// </summary>
        internal static string CubicKilometer {
            get {
                return ResourceManager.GetString("CubicKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³.
        /// </summary>
        internal static string CubicMeter {
            get {
                return ResourceManager.GetString("CubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi³.
        /// </summary>
        internal static string CubicMile {
            get {
                return ResourceManager.GetString("CubicMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm³.
        /// </summary>
        internal static string CubicMillimeter {
            get {
                return ResourceManager.GetString("CubicMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd³.
        /// </summary>
        internal static string CubicYard {
            get {
                return ResourceManager.GetString("CubicYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Decade {
            get {
                return ResourceManager.GetString("Decade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daPa.
        /// </summary>
        internal static string Decapascal {
            get {
                return ResourceManager.GetString("Decapascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbar.
        /// </summary>
        internal static string Decibar {
            get {
                return ResourceManager.GetString("Decibar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dl.
        /// </summary>
        internal static string Deciliter {
            get {
                return ResourceManager.GetString("Deciliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string DegreeCelsius {
            get {
                return ResourceManager.GetString("DegreeCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string DegreeFahrenheit {
            get {
                return ResourceManager.GetString("DegreeFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp(E).
        /// </summary>
        internal static string ElectricalHorsepower {
            get {
                return ResourceManager.GetString("ElectricalHorsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f/s.
        /// </summary>
        internal static string FeetPerSecond {
            get {
                return ResourceManager.GetString("FeetPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cc.
        /// </summary>
        internal static string FluidCubicCentimeter {
            get {
                return ResourceManager.GetString("FluidCubicCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPa.
        /// </summary>
        internal static string Gigapascal {
            get {
                return ResourceManager.GetString("Gigapascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW.
        /// </summary>
        internal static string Gigawatt {
            get {
                return ResourceManager.GetString("Gigawatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        internal static string Hectare {
            get {
                return ResourceManager.GetString("Hectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hl.
        /// </summary>
        internal static string Hectoliter {
            get {
                return ResourceManager.GetString("Hectoliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hm.
        /// </summary>
        internal static string Hectometer {
            get {
                return ResourceManager.GetString("Hectometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPa.
        /// </summary>
        internal static string Hectopascal {
            get {
                return ResourceManager.GetString("Hectopascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp.
        /// </summary>
        internal static string HydraulicHorsepower {
            get {
                return ResourceManager.GetString("HydraulicHorsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        internal static string ImperialGallon {
            get {
                return ResourceManager.GetString("ImperialGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string Joule {
            get {
                return ResourceManager.GetString("Joule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kbar.
        /// </summary>
        internal static string Kilobar {
            get {
                return ResourceManager.GetString("Kilobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kcal.
        /// </summary>
        internal static string Kilocalorie {
            get {
                return ResourceManager.GetString("Kilocalorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kJ.
        /// </summary>
        internal static string Kilojoule {
            get {
                return ResourceManager.GetString("Kilojoule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kPa.
        /// </summary>
        internal static string Kilopascal {
            get {
                return ResourceManager.GetString("Kilopascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klb.
        /// </summary>
        internal static string Kilopound {
            get {
                return ResourceManager.GetString("Kilopound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kt.
        /// </summary>
        internal static string Kilotonne {
            get {
                return ResourceManager.GetString("Kilotonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kW.
        /// </summary>
        internal static string Kilowatt {
            get {
                return ResourceManager.GetString("Kilowatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh.
        /// </summary>
        internal static string KilowattHour {
            get {
                return ResourceManager.GetString("KilowattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp(I).
        /// </summary>
        internal static string MechanicalHorsepower {
            get {
                return ResourceManager.GetString("MechanicalHorsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbar.
        /// </summary>
        internal static string Megabar {
            get {
                return ResourceManager.GetString("Megabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJ.
        /// </summary>
        internal static string MegaJoule {
            get {
                return ResourceManager.GetString("MegaJoule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mpa.
        /// </summary>
        internal static string Megapascal {
            get {
                return ResourceManager.GetString("Megapascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW.
        /// </summary>
        internal static string Megawatt {
            get {
                return ResourceManager.GetString("Megawatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWh.
        /// </summary>
        internal static string MegawattHour {
            get {
                return ResourceManager.GetString("MegawattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp(M).
        /// </summary>
        internal static string MetricHorsepower {
            get {
                return ResourceManager.GetString("MetricHorsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string MexicanPeso {
            get {
                return ResourceManager.GetString("MexicanPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µbar.
        /// </summary>
        internal static string Microbar {
            get {
                return ResourceManager.GetString("Microbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μg.
        /// </summary>
        internal static string Microgram {
            get {
                return ResourceManager.GetString("Microgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μmol.
        /// </summary>
        internal static string Micromole {
            get {
                return ResourceManager.GetString("Micromole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μS.
        /// </summary>
        internal static string Microsiemens {
            get {
                return ResourceManager.GetString("Microsiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string Mile {
            get {
                return ResourceManager.GetString("Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mbar.
        /// </summary>
        internal static string Millibar {
            get {
                return ResourceManager.GetString("Millibar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        internal static string Milligram {
            get {
                return ResourceManager.GetString("Milligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string Milliliter {
            get {
                return ResourceManager.GetString("Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string Millimeter {
            get {
                return ResourceManager.GetString("Millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmol.
        /// </summary>
        internal static string Millimole {
            get {
                return ResourceManager.GetString("Millimole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mS.
        /// </summary>
        internal static string Millisiemens {
            get {
                return ResourceManager.GetString("Millisiemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mol.
        /// </summary>
        internal static string Mole {
            get {
                return ResourceManager.GetString("Mole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ns.
        /// </summary>
        internal static string Nanosecond {
            get {
                return ResourceManager.GetString("Nanosecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oz.
        /// </summary>
        internal static string Ounce {
            get {
                return ResourceManager.GetString("Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ppb.
        /// </summary>
        internal static string PartsPerBillion {
            get {
                return ResourceManager.GetString("PartsPerBillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ppm.
        /// </summary>
        internal static string PartsPerMillion {
            get {
                return ResourceManager.GetString("PartsPerMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        internal static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‰.
        /// </summary>
        internal static string Permille {
            get {
                return ResourceManager.GetString("Permille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string Pound {
            get {
                return ResourceManager.GetString("Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbf.
        /// </summary>
        internal static string PoundForcePerSquareFoot {
            get {
                return ResourceManager.GetString("PoundForcePerSquareFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psi.
        /// </summary>
        internal static string PoundForcePerSquareInch {
            get {
                return ResourceManager.GetString("PoundForcePerSquareInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rad.
        /// </summary>
        internal static string Radian {
            get {
                return ResourceManager.GetString("Radian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Siemens {
            get {
                return ResourceManager.GetString("Siemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm².
        /// </summary>
        internal static string SquareCentimeter {
            get {
                return ResourceManager.GetString("SquareCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dm².
        /// </summary>
        internal static string SquareDecimeter {
            get {
                return ResourceManager.GetString("SquareDecimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft².
        /// </summary>
        internal static string SquareFoot {
            get {
                return ResourceManager.GetString("SquareFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sq in.
        /// </summary>
        internal static string SquareInch {
            get {
                return ResourceManager.GetString("SquareInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km².
        /// </summary>
        internal static string SquareKilometer {
            get {
                return ResourceManager.GetString("SquareKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m².
        /// </summary>
        internal static string SquareMeter {
            get {
                return ResourceManager.GetString("SquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi².
        /// </summary>
        internal static string SquareMile {
            get {
                return ResourceManager.GetString("SquareMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sq yd.
        /// </summary>
        internal static string SquareYard {
            get {
                return ResourceManager.GetString("SquareYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string Tonne {
            get {
                return ResourceManager.GetString("Tonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string UnitedStatesDollar {
            get {
                return ResourceManager.GetString("UnitedStatesDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        internal static string UsGallon {
            get {
                return ResourceManager.GetString("UsGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Watt {
            get {
                return ResourceManager.GetString("Watt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wh.
        /// </summary>
        internal static string WattHour {
            get {
                return ResourceManager.GetString("WattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string Yard {
            get {
                return ResourceManager.GetString("Yard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
